spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/split_pay_db
    username: postgres
    password: password


server:
  servlet:
    context-path: /api
